import { Link, useNavigate } from 'react-router-dom';
import { Button, Title } from '..';
import * as Dialog from '@radix-ui/react-dialog';
import Cyberpunk from '/images/time-clock.jpg'
import { Check, DoorClosed, GithubIcon, LinkedinIcon, X } from 'lucide-react';
import { ElementType } from 'react';

interface LinksProps {
    icon: ElementType;
    text: string;
}


export function Login() {

    const items: LinksProps[] = [
        {
            icon: <Check color="green" />,
            text: 'Our website was built by @leandrodearaujo',
        },
        {
            icon: <Check color="green" />,
            text: 'Our layout is unique',
        },
        {
            icon: <Check color="green" />,
            text: 'All images were generated by the leonardo.ai website',
        },
        {
            icon: <Check color="green" />,
            text: 'All our texts were generated by gpt chat',
        },
    ];

    return (
        <Dialog.Root>
            <Dialog.Trigger asChild>
                <Button color='violet'>
                    Sign In
                </Button>
            </Dialog.Trigger>
            <Dialog.Portal className='relative z-[99]'>
                <Dialog.Overlay className="bg-zinc-950/90 data-[state=open]:animate-overlayShow fixed inset-0 z-50" />
                <Dialog.Content className="container overflow-y-scroll data-[state=open]:animate-contentShow absolute top-1/2 left-1/2 max-h-full translate-x-[-50%] -translate-y-1/2  bg-[#0f0f0f] z-[999] p-[25px] shadow-[hsl(206_22%_7%_/_35%)_0px_10px_38px_-10px,_hsl(206_22%_7%_/_20%)_0px_10px_20px_-15px] focus:outline-none">
                    <div className='flex items-start gap-8 w-full justify-between max-lg:flex-col'>
                        <div className='w-96 h-screen max-lg:w-full max-lg:h-96 relative'>
                            <img className='h-full object-cover w-full max-lg:object-contain absolute inset-0' src={Cyberpunk} />
                        </div>
                        <div className='flex-1 w-full text-center space-y-4 items-start relative h-screen'>
                            <Title color='white' theme='base'>Functionality still in development</Title>
                            <Title color='gray' theme='base'>Don't worry, I am working as fast as possible to finish the development! 😁</Title>
                            <div className='bg-zinc-950 w-full h-max rounded-md p-4'>
                                <ul className='flex items-start gap-4 flex-col flex-wrap w-full'>
                                    {items.map((item) => (
                                        <li className='flex items-center gap-2'>
                                            {item.icon}
                                            <h1 className='max-sm:text-sm'>{item.text}</h1>
                                        </li>
                                    ))}
                                </ul>
                            </div>
                            <div className='pt-8 space-y-4'>
                                <Title color='white' theme='base'>Thank you for clicking on my site, I'm very happy!
                                    Enjoy and have access to our code and my social networks</Title>
                                <div className='space-x-4 text-center'>
                                    <Link>Github</Link>
                                    <Link>Linkedin</Link>
                                    <Link>Discord</Link>
                                    <Link>Whatsapp</Link>
                                </div>
                            </div>

                            <Dialog.Close asChild className='absolute bottom-10 text-center -translate-x-1/2 left-1/2 max-lg:relative max-lg:pt-16'>
                                <Title theme='base' color='gray'>Continue browsing our site</Title>
                            </Dialog.Close>
                        </div>

                    </div>
                    <Dialog.Close asChild>
                        <button
                            className="text-violet11 hover:bg-violet4 focus:shadow-violet7 absolute top-[10px] right-[10px] inline-flex h-[25px] w-[25px] appearance-none items-center justify-center rounded-full focus:shadow-[0_0_0_2px] focus:outline-none"
                            aria-label="Close"
                        >
                            <X />
                        </button>
                    </Dialog.Close>
                </Dialog.Content>
            </Dialog.Portal>
        </Dialog.Root >

    );
}